### PR TITLE
Extending ASPSP records table

### PR DESCRIPTION
**Pull request by n0rdy**

### CODE REVIEW

**Comment by spetrychenko** [comment]
will current csv file without new columns work with new aspsp record model?

**Comment by spetrychenko** [comment]
release notes weren't updated

**Comment by n0rdy** [comment]
> will current csv file without new columns work with new aspsp record model?

Yes, added a unit test for such a case (`AspspCsvServiceImplTest#importCsv_oldSchema`)

**Comment by n0rdy** [comment]
> release notes weren't updated

Added, thanks

**Pull request merged**
